name: scan

on: push

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/scan-secrets@latest
        with:
          scan-history: true
